#theme: jekyll-theme-cayman
#title: "Open-Domain, Content-based, Multi-modal Fact-checking of Out-of-Context Images via Online Resources"
#description: "Sahar Abdelnabi, Rakibul Hasan, and Mario Fritz <br> CISPA Helmholtz Center for Information Security"
#show_downloads: true

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Open-Domain, Content-based, Multi-modal Fact-checking of Out-of-Context Images via Online Resources" 
markdown: kramdown
theme: jekyll-theme-cayman
#description: "Sahar Abdelnabi, Rakibul Hasan, and Mario Fritz <br> CISPA Helmholtz Center for Information Security"
url: "https://s-abdelnabi.github.io/OoC-multi-modal-fc/" # the subpath of your site, e.g. /blog
baseurl: "/OoC-multi-modal-fc" # the subpath of your site, e.g. /blog
show_downloads: true
show_tagline: true
auth_color: "color:#FFFFFF"
aff_color: "color:#000000"
owner:
    name: Sahar Abdelnabi
    email: sahar.abdelnabi@cispa.saarland
author:
    name: Sahar Abdelnabi
    url: https://scholar.google.com/citations?user=QEiYbDYAAAAJ&hl=en

paper_url: "https://arxiv.org/pdf/2112.00061.pdf" 
datasetlink: "https://s-abdelnabi.github.io/OoC-multi-modal-fc/"
#plugins:
#    - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
