title: "Open-Domain, Content-based, Multi-modal Fact-checking of Out-of-Context Images via Online Resources" 
markdown: kramdown
theme: jekyll-theme-cayman
#description: "Sahar Abdelnabi, Rakibul Hasan, and Mario Fritz"
